{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Jeera.Print where

-- pretty-printer generated by the BNF converter

import Jeera.Abs
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
   Program statements -> prPrec i 0 (concatD [prt 0 statements])


instance Print Statement where
  prt i e = case e of
   DeviceDecl devicedecl -> prPrec i 0 (concatD [prt 0 devicedecl])

  prtList es = case es of
   [x] -> (concatD [prt 0 x , doc (showString ";")])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print DeviceDecl where
  prt i e = case e of
   SimpleDevice instancename simpledevicetype devicestatements -> prPrec i 0 (concatD [prt 0 instancename , doc (showString "=") , prt 0 simpledevicetype , doc (showString "{") , prt 0 devicestatements , doc (showString "}")])
   TwoPortDevice instancename devicestatements -> prPrec i 0 (concatD [prt 0 instancename , doc (showString "=") , doc (showString "Device") , doc (showString "{") , prt 0 devicestatements , doc (showString "}")])


instance Print SimpleDeviceType where
  prt i e = case e of
   Resistor  -> prPrec i 0 (concatD [doc (showString "Resistor")])
   Inductor  -> prPrec i 0 (concatD [doc (showString "Inductor")])
   Capacitor  -> prPrec i 0 (concatD [doc (showString "Capacitor")])


instance Print DeviceStatement where
  prt i e = case e of
   DeviceStatement lhsexpression rhsexpression -> prPrec i 0 (concatD [prt 0 lhsexpression , doc (showString "=") , prt 0 rhsexpression])

  prtList es = case es of
   [x] -> (concatD [prt 0 x , doc (showString ";")])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print LHSExpression where
  prt i e = case e of
   LHSExpression_value  -> prPrec i 0 (concatD [doc (showString "value")])
   LHSExpression_input  -> prPrec i 0 (concatD [doc (showString "input")])
   LHSExpression_output  -> prPrec i 0 (concatD [doc (showString "output")])
   LHSExpressionIdent id -> prPrec i 0 (concatD [prt 0 id])


instance Print RHSExpression where
  prt i e = case e of
   RHSExpressionSimpleExpression simpleexpression -> prPrec i 0 (concatD [prt 0 simpleexpression])
   RHSExpressionExpression expression -> prPrec i 0 (concatD [prt 0 expression])


instance Print SimpleExpression where
  prt i e = case e of
   ExpressionDouble d -> prPrec i 0 (concatD [prt 0 d])
   ExpressionInteger n -> prPrec i 0 (concatD [prt 0 n])


instance Print Expression where
  prt i e = case e of
   PortExpr portexpression -> prPrec i 0 (concatD [prt 0 portexpression])
   MathExpr mathexpression -> prPrec i 0 (concatD [prt 0 mathexpression])


instance Print PortExpression where
  prt i e = case e of
   PortExpression portname0 portname -> prPrec i 0 (concatD [doc (showString "(") , prt 0 portname0 , doc (showString ",") , prt 0 portname , doc (showString ")")])


instance Print MathExpression where
  prt i e = case e of
   MathExpression_1 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "*") , prt 0 expression])
   MathExpression_2 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "+") , prt 0 expression])
   MathExpression_3 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "/") , prt 0 expression])
   MathExpression_4 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "-") , prt 0 expression])
   MathExpression_5 mathexpression -> prPrec i 0 (concatD [doc (showString "(") , prt 0 mathexpression , doc (showString ")")])
   MathExpressionIdent id -> prPrec i 0 (concatD [prt 0 id])


instance Print InstanceName where
  prt i e = case e of
   InstanceName id -> prPrec i 0 (concatD [prt 0 id])


instance Print PortName where
  prt i e = case e of
   PortNameIdent id -> prPrec i 0 (concatD [prt 0 id])
   PortNameInteger n -> prPrec i 0 (concatD [prt 0 n])



