{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module Jeera.Print where

-- pretty-printer generated by the BNF converter

import Jeera.Abs
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Design where
  prt i e = case e of
   Design designstatements -> prPrec i 0 (concatD [prt 0 designstatements])


instance Print DesignStatement where
  prt i e = case e of
   DesignStatement devicedecl -> prPrec i 0 (concatD [prt 0 devicedecl])

  prtList es = case es of
   [x] -> (concatD [prt 0 x , doc (showString ";")])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print DeviceDecl where
  prt i e = case e of
   SimpleDevice instancename simpledeviceexpr -> prPrec i 0 (concatD [prt 0 instancename , doc (showString "=") , prt 0 simpledeviceexpr , doc (showString ";")])
   TwoPortDevice instancename twoportdeviceexpr -> prPrec i 0 (concatD [prt 0 instancename , doc (showString "=") , prt 0 twoportdeviceexpr , doc (showString ";")])


instance Print SimpleDeviceExpr where
  prt i e = case e of
   SimpleDeviceExpr devicetype devicestatements -> prPrec i 0 (concatD [prt 0 devicetype , doc (showString "{") , prt 0 devicestatements , doc (showString "}")])


instance Print DeviceType where
  prt i e = case e of
   DeviceType_Resistor  -> prPrec i 0 (concatD [doc (showString "Resistor")])
   DeviceType_Capacitor  -> prPrec i 0 (concatD [doc (showString "Capacitor")])
   DeviceType_Inductance  -> prPrec i 0 (concatD [doc (showString "Inductance")])
   DeviceType_Voltage  -> prPrec i 0 (concatD [doc (showString "Voltage")])


instance Print TwoPortDeviceExpr where
  prt i e = case e of
   TwoPortDeviceExpr devicestatements -> prPrec i 0 (concatD [doc (showString "Device") , doc (showString "{") , prt 0 devicestatements , doc (showString "}")])


instance Print DeviceStatement where
  prt i e = case e of
   DeviceStatementInputOutputExpression inputoutputexpression -> prPrec i 0 (concatD [prt 0 inputoutputexpression])
   DeviceStatementDeviceExpression deviceexpression -> prPrec i 0 (concatD [prt 0 deviceexpression])

  prtList es = case es of
   [x] -> (concatD [prt 0 x , doc (showString ";")])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print InputOutputExpression where
  prt i e = case e of
   InputExpression portexperssion -> prPrec i 0 (concatD [doc (showString "input") , doc (showString "=") , prt 0 portexperssion])
   OutputExpression portexperssion -> prPrec i 0 (concatD [doc (showString "output") , doc (showString "=") , prt 0 portexperssion])


instance Print DeviceExpression where
  prt i e = case e of
   DeviceExpression lhs rhs -> prPrec i 0 (concatD [prt 0 lhs , doc (showString "=") , prt 0 rhs])


instance Print LHS where
  prt i e = case e of
   LHSFunctionExpression functionexpression -> prPrec i 0 (concatD [prt 0 functionexpression])
   LHSVariable variable -> prPrec i 0 (concatD [prt 0 variable])


instance Print RHS where
  prt i e = case e of
   RHS expression -> prPrec i 0 (concatD [prt 0 expression])


instance Print FunctionExpression where
  prt i e = case e of
   FunctionExpression functionname variable -> prPrec i 0 (concatD [prt 0 functionname , doc (showString "(") , prt 0 variable , doc (showString ")")])


instance Print Expression where
  prt i e = case e of
   Expression_1 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "+") , prt 0 expression])
   Expression_2 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "-") , prt 0 expression])
   Expression_3 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "/") , prt 0 expression])
   Expression_4 expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , doc (showString "*") , prt 0 expression])


instance Print InstanceName where
  prt i e = case e of
   InstanceName id -> prPrec i 0 (concatD [prt 0 id])


instance Print Rvalue where
  prt i e = case e of
   RvalueDouble d -> prPrec i 0 (concatD [prt 0 d])
   RvalueIdent id -> prPrec i 0 (concatD [prt 0 id])
   RvalueInteger n -> prPrec i 0 (concatD [prt 0 n])


instance Print PortExperssion where
  prt i e = case e of
   PortExperssion expression -> prPrec i 0 (concatD [prt 0 expression])


instance Print Variable where
  prt i e = case e of
   Variable id -> prPrec i 0 (concatD [prt 0 id])


instance Print FunctionName where
  prt i e = case e of
   FunctionName id -> prPrec i 0 (concatD [prt 0 id])



